---
abstract: 'An RPM packager for perl modules'
author:
  - 'Sullivan Beck (sbeck@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: cpantorpm
no_index:
  directory:
    - t
    - inc
provides:
  Package::CPANtoRPM:
    file: CPANtoRPM.pm
    version: '1.01'
requires:
  Config: '0'
  IO::File: '0'
  POSIX: '0'
  perl: '5.006'
resources:
  repository: git://github.com/SBECK-github/MODULE_PKG.git
version: '1.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
