---
abstract: 'An RPM packager for perl modules'
author:
  - 'Sullivan Beck (sbeck@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Inter: '1.09'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-CPANtoRPM
no_index:
  directory:
    - t
    - inc
provides:
  App::CPANtoRPM:
    file: lib/App/CPANtoRPM.pm
    version: '1.14'
  cpantorpm:
    file: cpantorpm
    version: '1.14'
requires:
  IO::File: '0'
  POSIX: '0'
  locale: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/SBECK-github/App-CPANtoRPM/issues
  homepage: https://github.com/SBECK-github/App-CPANtoRPM
  repository: git://github.com/SBECK-github/App-CPANtoRPM.git
version: '1.14'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
