---
abstract: 'An RPM package for perl modules'
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: cpantorpm
requires:
  Config: 0
  IO::File: 0
  POSIX: 0
  perl: 5.00000
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
